
current GPU: NVIDIA A40
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "training.py", line 189, in <module>
    main()
  File "training.py", line 184, in main
    train(model, train_loader, val_loader, device, config)
  File "training.py", line 43, in train
    prediction = model(data)
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/practical-wise2223/MeshBody/BodyMeshGNN/model.py", line 315, in forward
    x = self.gnn(x, edge_index)
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/practical-wise2223/MeshBody/BodyMeshGNN/model.py", line 273, in forward
    x = batch_layer(x)
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 128 elements not 32
ModuleList(
  (0): GAT_NET(
    (conv): GATConv(16, 32, heads=4)
  )
  (1): GAT_NET(
    (conv): GATConv(128, 64, heads=4)
  )
  (2): GAT_NET(
    (conv): GATConv(256, 128, heads=4)
  )
  (3): GAT_NET(
    (conv): GATConv(512, 64, heads=4)
  )
)