current GPU: NVIDIA A40
using GPU: 3
































182it [01:05,  2.77it/s]
Traceback (most recent call last):
  File "training.py", line 258, in <module>
    main()
  File "training.py", line 234, in main
    model.load_state_dict(torch.load(f'runs/{config["experiment_name"]}/model_best.ckpt'))
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/u/home/zhousiy/.conda/envs/BodyMeshGNN/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/weight_prediction_5k/model_best.ckpt'